service: security-group-test-stack-2

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:
    SecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: sg-xxxxxxxxxxxxxxxxx
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0
